### ISSUE TITLE
Installation query

### ISSUE THREAD

**Issue by LorenzoSapora** [chinleung/nova-autofill#1]
Are you missing a step, during installation, of adding the class to nova?

I have your package installed, but can't seem to get `->autofill('sometable')` to work. And adding `use \ChinLeung\NovaAutofill\NovaAutofillServiceProvider` to my `NovaServiceProvider` under tools() isn't correct. Am I missing something?

I've also tried copy pasting your boot() into my nova service provider's boot(), to no effect.

**Comment by chinleung** [comment]
@LorenzoSapora You don't need to add anything after running the command since Laravel will auto discover the service provider. Are you receiving any errors? Also, please make sure you are creating from a parent model, otherwise it won't know how to autofill the values. :)

**Comment by LorenzoSapora** [comment]
Interesting, I've not seen a package that doesn't require some call (other than the autofill() you've got, of course).

No errors, I was trying to test, and dropped it into my development stack.

```php
fields(){
return [
            Text::make('Title', 'headline')
                ->autofill('headline')
                ->hideFromIndex()
                ->sortable(),
];
```

I cleared everything (for reference)

```bash
php artisan cache:clear;php artisan config:clear;php artisan route:clear;php artisan view:clear;php artisan optimize;php artisan clear-compiled;composer dump-autoload;php artisan config:cache;php artisan route:cache;php artisan view:cache;
```

And still couldn't get an autofill on the title field (when editing).

**Comment by chinleung** [comment]
> Interesting, I've not seen a package that doesn't require some call (other than the autofill() you've got, of course).
> 
> No errors, I was trying to test, and dropped it into my development stack.
> 
> ```
> fields(){
> return [
>             Text::make('Title', 'headline')
>                 ->autofill('headline')
>                 ->hideFromIndex()
>                 ->sortable(),
> ];
> ```
> 
> I cleared everything (for reference)
> 
> ```shell
> php artisan cache:clear;php artisan config:clear;php artisan route:clear;php artisan view:clear;php artisan optimize;php artisan clear-compiled;composer dump-autoload;php artisan config:cache;php artisan route:cache;php artisan view:cache;
> ```
> 
> And still couldn't get an autofill on the title field (when editing).

@LorenzoSapora It's not meant to fill anything on update. It's when you add a new resource via a parent model. For example, in the details view of a user, you add a new order, it will fill in the information of the user automatically for the new order that we are creating. Sorry for the confusion.

**Comment by LorenzoSapora** [comment]
Ah interesting. I, wrongly, assumed it was a general autofill. Thanks for your reply, and clearing up some confusion.
