### ISSUE TITLE
Is there any way to autofill nested relationships?

### ISSUE THREAD

**Issue by hassan-knopsmedia** [chinleung/nova-autofill#4]
For example, My event model belongs to a company and the company belongs to an address and address belongs to a city?

**Comment by chinleung** [comment]
@hassan-knopsmedia It is now possible with the release of [v1.1.1](https://github.com/chinleung/nova-autofill/releases/tag/v1.1.1).

```php
Text::make(__('Address'), 'address')
    ->autofill('relation1.relation2.attribute'),
```

**Comment by hassan-knopsmedia** [comment]
> @hassan-knopsmedia It is now possible with the release of [v1.1.1](https://github.com/chinleung/nova-autofill/releases/tag/v1.1.1).
> 
> ```
> Text::make(__('Address'), 'address')
>     ->autofill('relation1.relation2.attribute'),
> ```

@chinleung Thanks, Awesome man. Is it also possible to concatenate multiple attributes? 
`Text::make(__('Address'), 'address')
    ->autofill('address.street','address.house_number'),`

**Comment by chinleung** [comment]
@hassan-knopsmedia You can add an accessor to your model.

```php
public function getCombinedAddressAttribute()
{
    return "{$this->address->street} {$this->address->house_number}";
}
```

And then simply call the accessor in the autofill:

```php
Text::make(__('Address'), 'address')->autofill('combined_address')
```

**Comment by hassan-knopsmedia** [comment]
@chinleung But it doesn't work, I did exactly as you described:

      `public function getCombinedAddressAttribute()
	  {
		  return "{$this->company->address->street} {$this->company->address->house_number}/{$this->company->address->box_number},
		   {$this->company->address->city->postcode} {$this->company->address->city->name}";
	  }`
	
and in Nova

	`Text::make(__('Address'), 'address')
				->autofill('combined_address')
				->rules('required', 'string', 'max:255')
				->sortable(),`

**Comment by chinleung** [comment]
@hassan-knopsmedia To which model did you add the accessor?

Does it work if you try `Arr::get($model, 'combined_address');` in `php artisan tinker`?

**Comment by hassan-knopsmedia** [comment]
@chinleung It is in my Event Model.
Event Model:
`      
  class Event extends Model {
        /**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo|Company
	 */
	public function company()
	{
		return $this->belongsTo(Company::class);
	}

	public function getCombinedAddressAttribute()
	{
		return "{$this->company->address->street} {$this->company->address->house_number}/{$this->company->address->box_number},
	   {$this->company->address->city->postcode} {$this->company->address->city->name}";
	}
}`

In tinker I get  the address but in Nova:
`   $event = App\Models\Event::first();
=> App\Models\Event {#5105
     id: 103,
     title: "test",
     company_id: 22810,
     user_id: 201,
     contact_name: "test",
     address: "Testraten",
     phone_number: "+32465251088",
     remarks: "test",
     start: "2021-11-04 08:00:00",
     end: "2021-11-04 08:00:20",
     created_at: "2021-11-04 16:09:56",
     updated_at: "2021-11-04 16:11:30",
   }

Arr::get($event, 'combined_address');
=> """
   Aalbeeksestraat 68 /,\n
   \t   8510 ROLLEGEM
   ""
`

**Comment by hassan-knopsmedia** [comment]
@chinleung Thank you, Fixed it. It was my fault for adding an accessor to the Event Model instead of the Company Model Now it works like a charm. I am a junior dev still learning in my job though.
